- name: Create coturn directory
  become: true
  file:
    path: "{{ services_dir }}/coturn"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy coturn config
  become: true
  template:
    src: coturn.conf
    dest: "{{ services_dir }}/coturn/conf"
