---
  
###Configurate Synapse
- name: Create Synapse directory
  file:
    path: "{{ services_dir }}/synapse"
    state: directory
    owner: '991'
    group: '991'
    mode: 0775
    
- name: Generate Synapse env
  docker_container:
    name: synapse-cfg-gen
    image: matrixdotorg/synapse:latest
    interactive: true
    cleanup: true
    command: generate
    env:
      SYNAPSE_REPORT_STATS=no
      SYNAPSE_SERVER_NAME="{{ synapse_server_name }}"
    mounts:
      - target: /data
        source: "{{ services_dir }}/synapse"
        type: bind

- name: Copy Synapse config
  template:
    src: homeserver.yaml
    dest: "{{ services_dir }}/synapse/homeserver.yaml"   

- name: Add REST auth provider if needed
  copy:
    src: files/rest_auth_provider.py
    dest: "{{ services_dir }}/synapse/rest_auth_provider.py"
    owner: root
    group: root
    mode: '0755'
  when: mxisd_enabled | bool

###Configurate DB

- name: Configurate Postgre
  include_tasks: psql.yml

###Configurate optional services
##mxisd
- name: Install mxisd
  include_tasks: mxisd.yml
  when: mxisd_enabled | bool
  
##Coturn
- name: Install coturn
  include_tasks: coturn.yml
  when: coturn_enabled | bool
  

#Setting up Nginx

- name: Install Nginx
  include_tasks: nginx.yml
  when: nginx_enabled | bool  

#Setting up riot-web

- name: Install Riot
  include_tasks: riot.yml
  when: riot_enabled | bool  

    
 ###Configurate docker-compose file   
- name: Copy docker-compose file
  become: true
  template:
    src: docker-compose.yaml
    dest: "{{ services_dir }}/docker-compose.yaml"
    
    
###Start services
- name: Start services
  docker_compose:
    project_src: "{{ services_dir }}"
  when: start_services_after_install | bool  
    
###END
- debug:
    msg:
    - "Generated credentials:"
    - "Postgre:"
    - "  User: postgre"
    - "  Pass: {{ psql_pass }}"
    - "  User: synapse"
    - "  Pass: {{ synapse_db_pass }}"
    - "Synapse"
    - "Turn secret: {{ coturn_secret }}"
    - "Registration_secret: {{ synapse_registration_shared_secret }}"
    - "Macaroon secret: {{ synapse_macaroon_secret_key }}"
    - "Form secret: {{ synapse_form_secret }}"

