---
- name: Try to install Riot
  block:
    - name: Create riot directory
      file:
        path: "{{ services_dir }}/nginx/html/riot-web"
        state: directory
        owner: root
        group: root
        mode: 0775
        recurse: yes
        
    - name: Get latest riot release
      get_url:                                                           
        url: "https://github.com/vector-im/riot-web/releases/download/{{riot_version}}/riot-{{riot_version}}.tar.gz"                       
        dest: "/tmp/riot-web-latest.tar.gz"   

    - name: "Extract riot-web to {{ services_dir }}/nginx/html/riot-web/"
      unarchive:
        remote_src: true
        src: "/tmp/riot-web-latest.tar.gz"
        dest: "{{ services_dir }}/nginx/html/riot-web/"
        extra_opts: [--strip-components=1] 

    - name: Copy riot config
      template:
        src: riot.json
        dest: "{{ services_dir }}/nginx/html/riot-web/config.json"
  when: nginx_enabled | bool  

- name: Cant install Riot
  debug:
    msg: 'Cant install Riot without Nginx'
  when: not nginx_enabled | bool
