---
  
- name: Create coturn directory
  become: true
  file:
    path: "{{ services_dir }}/coturn"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy coturn config
  become: true
  template:
    src: coturn.conf
    dest: "{{ services_dir }}/coturn/conf"
    
- name: Start coturn
  docker_container:
    name: coturn
    image: monogramm/docker-coturn:latest
    mounts:
      - target: /srv
        source: "{{ services_dir }}/coturn"
        type: bind
    network_mode: host
