---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true
  roles:
    - ansible-role-docker-ce
    - ansible-synapse-docker

- name: "Set up a Coturn server"
  hosts: "{{ target if target is defined else 'coturn_servers' }}"
  become: true
  roles:
    - ansible-role-docker-ce
    - ansible-role-coturn

- name: "Set up a OpenLDAP server"
  hosts: "{{ target if target is defined else 'ldap_servers' }}"
  become: true
  roles:
    - ansible-role-docker-ce
    - ansible-role-ldap

- name: "Set up a Nginx server"
  hosts: "{{ target if target is defined else 'nginx_servers' }}"
  become: true
  roles:
    - ansible-nginx-revproxy
    - ansible-letsencrypt-nginx-revproxy
  vars:
    nginx_revproxy_sites:
      default:
        ssl: false
        letsencrypt: false
      synapse_server_name:
        domains:
          - {{nginx_proxy_domain}}
        upstreams:
          - { backend_address: {{synapse_server_name}}, backend_port: 80 }
        ssl: true
        letsencrypt: true
