---
- name: Pre tasks
  hosts: all
  become: true
  tasks:
  - name: Disable Fingerprint checking that may be enabled.  When enabled, causes SSH issues.
    command: authconfig --disablefingerprint --update
    ignore_errors: true

- name: "Set up a Matrix server"
  hosts: matrix_servers
  become: true
  roles:
    - ansible-synapse-docker

- name: "Set up a OpenLDAP server"
  hosts: ldap_servers
  become: true
  roles:
    - { role: ansible-role-ldap, when: ldap_enabled | bool}

- name: "Set up a Proxy server"
  hosts: nginx_servers
  become: true
  roles:
    - ansible-role-synapse-nginx
    - { role: ansible-role-coturn, when: coturn_enabled}
