---
- name: "Set up"
  hosts: all
  become: true
  roles:
    - ansible-role-wireguard
  vars:
    wireguard_remote_directory: "/etc/wireguard"
    wireguard_port: "51820"
    wireguard_interface: "wg0"
    wireguard_allowed_ips: "10.1.0.0/24"
