---
- name: Pre tasks
  hosts: all
  become: true
  pre_tasks:
    - name: Disable Fingerprint checking that may be enabled.  When enabled, causes SSH issues.
      command: authconfig --disablefingerprint --update

- name: Updating Matrix-Synapse
  hosts: matrix_servers
  become: true
  tasks:
    - name: Update all packages
      package: name=* state=latest

    - name: Shutting down docker containers
      docker_compose:
        project_src: "{{ services_dir }}"
        state: absent

    - name: Updating docker containers
      docker_compose:
        project_src: "{{service_dir}}"

- name: Updating Coturn servers
  hosts: coturn_servers
  become: true
  tasks:
    - name: Update all packages
      package: name=* state=latest

    - name: Stopping coturn
      docker_container:
        name: coturn
        state: absent

    - name: Starting coturn
      docker_container:
        name: coturn
        image: monogramm/docker-coturn:latest
        mounts:
          - target: /srv
            source: "{{ services_dir }}/coturn"
            type: bind
        network_mode: host
- name: Updating
  hosts: ldap_server
  tasks:
    - name: Stopping LDAP
      docker_container:
        name: openldap_server
        state: absent
    - name: Stopping phpLDAPadmin
      docker_container:
        name: openldap_admin
        state: absent
      when: LDAP_PHP_ADMIN | bool
  roles:
    - ansible-role-ldap

- name: Updating Nginx
  hosts: nginx_servers
  become: true
  tasks:
    - name: Update all packages
      package: name=* state=latest
