---
- name: Getting interface name
  set_fact:
    firewall_internal_interface: "{{ item }}"
  when: hostvars[inventory_hostname]['ansible_%s' | format(item)]|json_query('ipv4.address') == "{{ ldap_internal_ip }}"
  loop:
    - "{{ ansible_interfaces }}"

- name: Setup Firewalld
  block:
  - name: Set internal interface
    firewalld:
      zone: internal
      interface: "{{ firewall_internal_interface }}"
      permanent: yes
      state: enabled

  - name: Allow internal LDAP
    firewalld:
      zone: internal
      service: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - ldap
      - ldaps

  - name: Bounce firewalld
    service:
      name: firewalld
      state: restarted
  when: ansible_os_family == 'RedHat'

- name: Setup UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    interface: "{{ firewall_internal_interface }}"
  loop:
    - 389
    - 636
  when: ansible_os_family == 'Debian'

- name: Create LDAP directory
  file:
    path: "{{ services_dir }}/ldap"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ services_dir }}/ldap/docker-compose.yaml"

- name: Start services
  docker_compose:
    project_src: "{{ services_dir }}/ldap"

- debug:
    msg:
    - "LDAP creds:"
    - "  Domain: {{ LDAP_DOMAIN }}"
    - "  LDAP user: admin"
    - "  LDAP password: {{ LDAP_ADMIN_PASSWORD }}"
