---
- name: Create LDAP directory
  become: true
  file:
    path: "{{ services_dir }}/ldap"
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy docker-compose file
  become: true
  template:
    src: docker-compose.yaml
    dest: "{{ services_dir }}/ldap/docker-compose.yaml"

- name: Start services
  docker_compose:
    project_src: "{{ services_dir }}/ldap"

- debug:
    msg:
      - 'LDAP creds:'
      - 'Domain: {{LDAP_DOMAIN}}'
      - 'LDAP user: admin'
      - 'LDAP password: {{LDAP_ADMIN_PASSWORD}}'
