version: '3'

services:
  coturn:
    image: monogramm/docker-coturn:latest
    container_name: coturn
    environment:
      - LISTENING_PORT=3478
      #-  TLS_LISTENING_PORT=5349
      - LISTEN_IPS={{ansible_default_ipv4.address}}
      - RELAY_IP={{ansible_default_ipv4.address}}
      #- LONG_TERM_CREDENTIALS=1
      - STATIC_AUTH_SECRET={{coturn_secret}}
      # - TLS_CERT=/srv/cert.pem
      # - TLS_KEY=/srv/pkey.pem
      - NO_CLI=1
      - REALM={{synapse_server_name}}
      - VERBOSE=1
      - DEBUG=0
      - PROD=1
      - MIN_PORT=60535
      - MAX_PORT=62535
      #-  USER_DB=/srv/turnserver/db/turndb.sqlite
      #-  LOG_FILE=/srv/turnserver/logs/turn.log
      #-  PID_FILE=/srv/turnserver/turn.pid
    restart: unless-stopped
    network_mode: "host"
