#Hosts to install matrix-synapse bundle
all:
  hosts:
  vars:
    ansible_ssh_user: user

  children:
    certbot:
      hosts:
        matrix.local:
          certbot_certs: matrix.local
    matrix_servers:
      hosts:
        matrix.local:
          ###Install options
          services_dir: /opt/matrix
          coturn_enabled: true
          nginx_enabled: true
          riot_enabled: false
          riot_version: v1.5.5
          start_services_after_install: true

          ###Postgres
          psql_pass: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
          synapse_db_pass: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
          #Default synapse user and db: "synapse"

          ###Synapse
          synapse_server_name: matrix.local #Used in matrix users name, e.g @user:matrix.local
          ###To use internal coturn server set "synapse_coturn_address: coturn". Another way set to coturn server address.
          synapse_coturn_address: coturn

          #Create matrix user with admin privs. To use this option set 'start_services_after_install' to true
          synapse_create_admin_user: true
          synapse_admin_user: synapse_admin
          synapse_admin_pass: "{{ lookup('password', 'dev/null length=14 chars=ascii_letters,digits') }}"

          #Enable messanges cleanup script
          synapse_cleanup_enabled: true

          coturn_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
          synapse_registration_shared_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
          synapse_macaroon_secret_key: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
          synapse_form_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"

          ###Nginx
          nginx_synapse_domain: {{synapse_server_name}} #By default using synapse server name
          nginx_tls_disabled: false
