version: '3'

services:
  synapse:
    image: matrixdotorg/synapse
    restart: unless-stopped
    volumes:
      - {{ services_dir }}/synapse:/data
    depends_on:
      - db
    ports:
      - {{ synapse_internal_ip }}:8008:8008/tcp

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD={{psql_pass}}
    volumes:
      - {{ services_dir }}/schemas:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
