#https://github.com/kamax-matrix/mxisd

matrix:
  domain: '{{synapse_server_name}}'

server:
  name: '{{synapse_server_name}}'
  publicUrl: 'https://{{synapse_server_name}}'

key:
  path: '/var/mxisd/sign.key'

storage:
  provider:
    sqlite:
      database: '/var/mxisd/mxisd.db'

ldap:
  enabled: true
  connection:
    host: '{{mxisd_ldap_host}}'
    port: {{mxisd_ldap_port}}
    bindDn: {{mxisd_ldap_bindDn}}
    bindPassword: '{{mxisd_ldap_bindPassword}}'
    baseDNs: {{mxisd_ldap_baseDNs}}
    ldap.attribute.uid.type: 'mxisd_ldap_ldap.attribute.uid.type'
    ldap.attribute.uid.value: 'mxisd_ldap_ldap.attribute.uid.value'
    ldap.attribute.name: 'mxisd_ldap_ldap.attribute.name'

dns:
  overwrite:
    homeserver:
      client:
        - name: '{{synapse_server_name}}'
          value: 'http://synapse:8008'
