---
#Default variables

## Generate random secret for coturn config
coturn_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
## Coturn server domain name
coturn_server_address: hostvars[inventory_hostname]
## Coturn dir location
services_dir: /opt
