---
#Default variables

## Generate random secret for coturn config
coturn_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"

cert: /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem
privkey: /etc/letsencrypt/live/{{ fqdn }}/privkey.pem
