---
- name: Setup firewalld: 443
  firewalld:
    service: {{ item }}
    permanent: yes
    state: enabled
  loop:
    - 'https'
    - 'http'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Enable Web services UFW rule
  ufw:
    rule: allow
    port: {{ item }}
    proto: tcp
  loop:
    - 443
    - 80
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Download certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /bin/certbot-auto
    mode: '0755'
    owner: 'root'

- name: "Certbpt creates certificate"
  command: "certbot-auto certonly --nginx --register-unsafely-without-email --agree-tos -d {{ fqdn }}"
  args:
    creates: /etc/letsencrypt/live/{{ cert_item }}

- name: Copy certbot renewal service
  template:
    src: certbot_renewal.service
    dest: /usr/lib/systemd/system/certbot-renewal.service

- name: Copy certbot renewal timer
  template:
    src: certbot_renewal.timer
    dest: /usr/lib/systemd/system/certbot-renewal.timer

- name: Enable certbot renewal service
  systemd:
    name: certbot-renewal.service
    enabled: yes
    daemon-reload: yes

- name: Enable certbot renewal timer
  systemd:
    name: certbot-renewal.timer
    state: started
    enabled: yes
