---
- name: Setup firewalld
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: setup firewalld
  firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled

- name: Bounce firewalld
  service:
    name: firewalld
    state: restarted

- name: Check if certbot already exist.
  stat:
    path: /bin/certbot-auto
  register: certbot_exist

- name: Download certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /bin/certbot-auto
    mode: '0755'
    owner: 'root'
  when: not certbot_exist.stat.exists

- include_tasks: create-cert-standalone.yaml
  with_items: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert_item

- name: Add certbot renewal service
  include_tasks: certbot-renewal.yaml
