---
- name: Enable coturn firewalld rule
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - '60535-62535/udp'
    - '3478/tcp'
  when: ansible_os_family == 'RedHat'

- name: Enable coturn UFW rule
  ufw:
    rule: allow
    port: 60535:62535
    proto: udp
  when: ansible_os_family == 'Debian'

- name: Enable coturn UFW rule
  ufw:
    rule: allow
    port: 3478
    proto: tcp
  when: ansible_os_family == 'Debian'

- name: Get public IP
  ipify_facts:
  register: public_ip

- name: Install Coturn
  package:
    name: coturn
    state: latest

- name: Configure coturn server
  template:
    src: turnserver.conf
    dest: /etc/coturn/turnserver.conf.j2

- name: Start and enable Coturn
  service:
    name: coturn
    state: started
    enabled: true
