---
#Default variables

###Install options
services_dir: /opt/matrix
start_services_after_install: false

###Postgres
psql_pass: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
synapse_db_pass: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
#Default synapse user and db: "synapse"

###Synapse
synapse_registration_enabled: false #Allow users to register by them-self
synapse_server_name: matrix.local #Used in matrix users name, e.g @user:matrix.local
###Set to coturn server address. Get synapse public ip if blank.
synapse_coturn_address: ''

#Enable messanges cleanup script
synapse_cleanup_enabled: true
synapse_create_admin_user: true

synapse_admin_user: synapse_admin
synapse_admin_pass: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"

coturn_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
synapse_registration_shared_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
synapse_macaroon_secret_key: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
synapse_form_secret: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"

#LDAP
synapse_ldap_enabled: true
synapse_ldap_server: matrix.local:389
synapse_ldap_base: dc=matirx
synapse_ldap_bind_dn: cn=admin,dc=matirx
synapse_ldap_bind_pass: "{{LDAP_ADMIN_PASSWORD}}"
