name: Ansible role validation
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Ansible linting
      run: docker run --rm -v ${PWD}:/mnt:ro haxorof/ansible-lint .
