---
- name: Setup firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 'https'
    - 'http'
  when: ansible_os_family == 'RedHat'

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: Enable Web services UFW rule
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 443
    - 80
  when: ansible_os_family == 'Debian'
