---
- name: Setup firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 'https'
    - 'http'
  register: firewall
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat and firewall.changed'

- name: Enable Web services UFW rule
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 443
    - 80
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
